/******************************************************************************************
Copyright (c) 2007 Ultracell.  All Rights Reserved.
FileName: calcs
Ultracell Document Number:  UCSWD200024

Description: general calculations

Revision History
Rev.   Date         Author  Description
1.00   12/03/2007   DR      Production release
1.01   03/26/2008   DR      field upgrade variable changes

************************ includes *******************************************************/
#include <include/Main.h>
/************************ extern variables ***********************************************/

// IN MAIN

extern uint8_t burner_fuel;
extern uint8_t cart_enable;
extern uint8_t blower_enable;

// in ADC ISR
extern float FC_volts;
extern float FC_Current;
extern float RS_Batt_V;
extern float CO_Batt_V;
extern float Load_Current;
extern float Output_volts;

// in initialize
extern float main_fuel_flow;
extern uint8_t load;

// start
extern float air;
//extern float startup_batt_V;

//loadfollow
extern float O2_Cons;

//Options

//run
extern float FC_power;

//calcs
float O2_util;
//float old_FC_Current;
float burn_stoich;

unsigned int  FC_peak_current;
unsigned int  Load_peak_current;
unsigned int min_FC_volts;
unsigned int min_Output_volts;


float load_power;
float H2_Util;

float FCRofst;


float FC_R;

int old_FC_Current;
float avg_FC_power;
extern int AtRate;

//### New Additions for 'tfcp' calculation:
//Timing.c
extern int tfcp;
extern int fc_run_temp_max;
extern float TC1_temp;
extern float Net_Power_Limit_Max;

extern int Feature2;
//extern uint8_t USB_on;
extern uint8_t USB_Status;

//Formulas.c
extern unsigned int ALT_Temp;

extern unsigned int Altitude;

/************************ extern functions ***********************************************/


/************************ internal functions **********************************************/
void calcs(void);
#include <math.h>
/************************ define constants ***********************************************/

/************************ relocatable program code ***************************************/
void calcs(void)
{
float H2_4burn;
float H2_Tot;
float H2_cons ;// 15 = # cells in stack
float O2_tot;
float O2_4burn;


// detect the minimum voltages and max currents the system sees each cycle.

  unsigned int tms;

  if(FC_volts < 0)FC_volts = 0;
  tms = (unsigned int)(FC_volts*1000);
  if(tms < min_FC_volts)min_FC_volts = tms;
  else if (min_FC_volts < 25000) min_FC_volts += 10; //increment min volts if no comunication

  if(Output_volts < 0)Output_volts = 0;
  tms = (unsigned int)(Output_volts*1000);
  if(tms < min_Output_volts)min_Output_volts = tms;
  else if (min_Output_volts < 40000) min_Output_volts += 10; //increment min volts if no comunication

  if(FC_Current < 0)FC_Current=0;
  tms = (unsigned int)(FC_Current*1000);
  if(tms > FC_peak_current)FC_peak_current = tms;
  else if (FC_peak_current > 10) FC_peak_current -= 10; //decrement peak current if no comunication

  if(Load_Current < 0) Load_Current=0;
  tms = (unsigned int)(Load_Current*1000);
  if(tms > Load_peak_current)Load_peak_current = tms;
  else if (Load_peak_current > 10) Load_peak_current -= 10; //decrement peak current if no comunication


  load_power = (Load_peak_current*0.001*min_Output_volts*0.001);

  AtRate = (int)(-10*(Load_Current*Output_volts)); //[100mW]
  //AtRate = (int)(- Load_Current*10); //[A}*10

  if(!DCrun)load_power = 0;


  FC_power = FC_Current*FC_volts;

  avg_FC_power = (FC_power + (NumSamples_AvePower-1.0)*avg_FC_power) / (float)NumSamples_AvePower; // NumSamples_AvePower (=20) sample Moving Average, recalculated every 10 ms.
  //### End Change
  

   
   //FC_R  P < 32 = = -0.000619340x3 + 0.054134732x2 - 1.647545088x + 19.699155076
    //FC_R  P > 32 = = -0.000013900x3 + 0.002815999x2 - 0.205376884x + 6.173148680
  if (avg_FC_power < 32)   //Pol Curve for 12 Cell using 90%
   {  FC_R = -0.000619340*avg_FC_power*avg_FC_power*avg_FC_power + 0.054134732*avg_FC_power*avg_FC_power -1.647545088*avg_FC_power + 19.699155076; }
   else 
   {  FC_R = -0.000013900*avg_FC_power*avg_FC_power*avg_FC_power +0.002815999*avg_FC_power*avg_FC_power - 0.205376884*avg_FC_power+ 6.173148680; }
 
  if(FC_R>8.0)FC_R=8.0;
   if(FC_R<0.6)FC_R=0.6;
   FC_R += FCRofst;
  if(load_power < 0)load_power = 0;

  if(mode == Sleep)
  {
    min_FC_volts = (unsigned int) (FC_volts*1000);
    min_Output_volts =  (unsigned int) (Output_volts*1000);
    FC_peak_current = 0;
    load_power = 0;
    FC_Current = 0;
  }

  //these calculations are used for determining fuel and air flow

  H2_Tot = ((18.0 * main_fuel_flow)/1000);// H2 generated by the processor in sccm
  H2_cons = (0.006969 * FC_Current * ((float)(cells)));// 12 = # cells in stack in sccm
  if(FC_Current >.2) H2_Util = (H2_cons / H2_Tot);// only display H2_Util below .2 since current
                                                  //below that point is noisey

  if(FC_Current <.2)H2_Util = 0;
  if(H2_Util > 100)H2_Util = 0;

  H2_4burn = (H2_Tot * 1.0881 - H2_cons); // includes contribution from CO and methanol

  if (air > 0.3)
  {  
   O2_tot = (air * .21);// oxygen available at sea level
   O2_Cons = (.5 * H2_cons);//sccm
   O2_4burn = (O2_tot - O2_Cons);// oxygen left for the burner
   O2_util = (O2_Cons / O2_tot);
  }
  else O2_util = 0.0;

  if (O2_util > 100)O2_util = 100;
  if (burner_fuel == true) burn_stoich = (air / (0.0457*main_fuel_flow)); 
  else burn_stoich = O2_4burn/(H2_4burn * 0.5);//0.286 mmol/min per mL/hr

//### Data Overflow bugfix
  if (main_fuel_flow == 0) 
  {  burn_stoich = 0; }

//### Moved from Run.c
// Set Top Fuel-Cell Power variable (Gross-Power Limit), based on FCS Temperature, and Altitude:

  if (!(Debugging) && (Feature2>0)) tfcp = Feature2;
    else
        tfcp = (int) (((fc_run_temp_max + 4) - TC1_temp) * 1.5 + 68.0); // if temp is 175 then max power 65W, if 180 then max power is 35W if FCsp is 173
  if (tfcp > 68) tfcp=68; //68max FC power

//### End Move comment

}

/*****************************************************************************************/
